import { MenuConfig } from "@/types/menu-types";

export const menuStructure: MenuConfig = {
  modules: [
    {
      id: "accesos",
      key: "accesos",
      label: "Accesos",
      icon: "door-open",
      order: 1,
      columns: 4,
      sections: [
        {
          id: "entradas-salidas",
          key: "entradas_salidas",
          label: "Entradas & Salidas",
          order: 1,
          column: 1,
          items: [
            {
              key: "nuevo_acceso",
              label: "+ Nuevo Acceso",
              type: "link",
              href: "/accesos",
              order: 1,
            },
            {
              key: "entradas",
              label: "Entradas",
              type: "link",
              href: "/bitacoras?status=entrada",
              order: 2,
            },
            {
              key: "salidas",
              label: "Salidas",
              type: "link",
              href: "/bitacoras?status=salida",
              order: 3,
            },
            {
              key: "accesos_hoy",
              label: "Accesos de hoy",
              type: "link",
              href: "/bitacoras?date=today",
              order: 4,
            },
            {
              key: "todos_accesos",
              label: "Todos",
              type: "link",
              href: "/bitacoras",
              order: 5,
            },
          ],
        },
        {
          id: "vehiculos",
          key: "vehiculos",
          label: "Vehículos",
          order: 2,
          column: 2,
          items: [
            {
              key: "vehiculos_dentro",
              label: "Dentro",
              type: "link",
              href: "/bitacoras?tab=vehiculos&status=entrada",
              order: 1,
            },
            {
              key: "vehiculos_todos",
              label: "Todos",
              type: "link",
              href: "/bitacoras?tab=vehiculos",
              order: 2,
            },
          ],
        },
        {
          id: "vehiculos-config",
          key: "vehiculos_config",
          label: "Configuración",
          order: 3,
          column: 2,
          items: [
            {
              key: "tipo_vehiculos",
              label: "Tipo de vehículos",
              type: "config",
              order: 1,
            },
          ],
        },
        {
          id: "equipos",
          key: "equipos",
          label: "Equipos",
          order: 4,
          column: 3,
          items: [
            {
              key: "equipos_dentro",
              label: "Dentro",
              type: "link",
              href: "/bitacoras?tab=equipos&status=entrada",
              order: 1,
            },
            {
              key: "equipos_todos",
              label: "Todos",
              type: "link",
              href: "/bitacoras?tab=equipos",
              order: 2,
            },
          ],
        },
        {
          id: "equipos-config",
          key: "equipos_config",
          label: "Configuración",
          order: 5,
          column: 3,
          items: [
            {
              key: "tipo_vehiculos_equipo",
              label: "Tipo de vehículos",
              type: "config",
              order: 1,
            },
          ],
        },
        {
          id: "gafetes-lockers",
          key: "gafetes_lockers",
          label: "Gafetes & Lockers",
          order: 6,
          column: 4,
          items: [
            {
              key: "gafetes_libres",
              label: "Libres",
              type: "option",
              order: 1,
            },
            {
              key: "gafetes_ocupados",
              label: "Ocupados",
              type: "option",
              order: 2,
            },
            { key: "gafetes_todos", label: "Todos", type: "option", order: 3 },
          ],
        },
        {
          id: "gafetes-config",
          key: "gafetes_config",
          label: "Configuración",
          order: 7,
          column: 4,
          items: [
            {
              key: "config_gafetes",
              label: "Gafetes",
              type: "config",
              order: 1,
            },
            {
              key: "config_lockers",
              label: "Lockers",
              type: "config",
              order: 2,
            },
            {
              key: "config_gafetes_lockers",
              label: "Configuración gafetes y lockers",
              type: "config",
              order: 3,
            },
          ],
        },
      ],
    },
    {
      id: "pases-entrada",
      key: "pases_entrada",
      label: "Pases de Entrada",
      icon: "ticket",
      order: 2,
      columns: 3,
      sections: [
        {
          id: "pases-de-entrada",
          key: "pases_de_entrada",
          label: "Pases de Entrada",
          order: 1,
          column: 1,
          items: [
            {
              key: "nuevo_pase",
              label: "+ Nuevo Pase",
              type: "link",
              href: "/pase-entrada",
              order: 1,
            },
            {
              key: "pases_activos",
              label: "Activos",
              type: "link",
              href: "/pases?status=activos",
              order: 2,
            },
            {
              key: "pases_por_autorizar",
              label: "Por autorizar",
              type: "link",
              href: "/pases?status=por_autorizar",
              order: 3,
            },
            {
              key: "pases_en_proceso",
              label: "En Proceso",
              type: "link",
              href: "/pases?status=en_proceso",
              order: 4,
            },
            {
              key: "todos_pases",
              label: "Todos",
              type: "link",
              href: "/pases",
              order: 5,
            },
          ],
        },
        {
          id: "pases-reportes",
          key: "pases_reportes",
          label: "Reportes",
          order: 2,
          column: 1,
          items: [
            {
              key: "reporte_de_pases",
              label: "Reporte de pases",
              type: "option",
              order: 1,
            },
          ],
        },
        {
          id: "pases-configuracion",
          key: "pases_configuracion",
          label: "Configuración",
          order: 3,
          column: 1,
          items: [
            {
              key: "tipo_de_perfiles",
              label: "Tipo de Perfiles",
              type: "option",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      id: "caseta",
      key: "caseta",
      label: "Caseta",
      icon: "building",
      order: 3,
      columns: 3,
      sections: [
        {
          id: "turnos",
          key: "turnos",
          label: "Turnos",
          order: 1,
          column: 1,
          items: [
            {
              key: "turno_inicio_cierre",
              label: "Inicio/Cierre",
              type: "link",
              href: "/turnos",
              order: 1,
            },
          ],
        },
        {
          id: "turno-reportes",
          key: "turno_reportes",
          label: "Reportes",
          order: 2,
          column: 1,
          items: [
            {
              key: "turno_reportes",
              label: "Reporte de asistencia",
              type: "option",
              order: 1,
            },
          ],
        },
        {
          id: "turno-configuracion",
          key: "turno_configuracion",
          label: "Configuración",
          order: 3,
          column: 1,
          items: [
            {
              key: "turno_horarios",
              label: "Horarios",
              type: "option",
              order: 1,
            },
          ],
        },
        {
          id: "turno-notas",
          key: "turno_notas",
          label: "Notas",
          order: 1,
          column: 2,
          items: [
            {
              key: "turno_nueva_nota",
              label: "+ Nueva Nota",
              type: "link",
              href: "/notas?action=nueva_nota",
              order: 1,
            },
            {
              key: "turno_notas_pendientes",
              label: "Pendientes",
              type: "link",
              href: "/notas?status=abierto",
              order: 2,
            },
            {
              key: "turno_cerrada_nota",
              label: "Cerradas",
              type: "link",
              href: "/notas?status=cerrado",
              order: 3,
            },
            {
              key: "turno_todas_nota",
              label: "Todos",
              type: "link",
              href: "/notas",
              order: 4,
            },
          ],
        },
      ],
    },
    {
      id: "seguridad",
      key: "seguridad",
      label: "Seguridad",
      icon: "alert",
      order: 4,
      columns: 3,
      sections: [
        {
          id: "incidencias",
          key: "incidencias",
          label: "Incidencias",
          order: 1,
          column: 1,
          items: [
            {
              key: "nuevo_incidente_seguridad",
              label: "+ Nuevo Incidente",
              type: "link",
              href: "/incidencias?tab=incidencia&action=nueva_incidencia",
              order: 1,
            },
            {
              key: "incidencias_abiertas",
              label: "Abiertas",
              type: "link",
              href: "/incidencias?tab=incidencia&status=abierto",
              order: 2,
            },
            {
              key: "incidencias_cerradas",
              label: "Cerradas",
              type: "link",
              href: "/incidencias?tab=incidencia&status=cerrado",
              order: 3,
            },
            {
              key: "incidencias_todas",
              label: "Todos",
              type: "link",
              href: "/incidencias?tab=incidencia",
              order: 4,
            },
          ],
        },
        {
          id: "configuracion-incidentes",
          key: "configuracion-incidentes",
          label: "Configuración",
          order: 2,
          column: 1,
          items: [
            {
              key: "categorias_incidencias",
              label: "Categorías",
              type: "option",
              order: 1,
            },
            {
              key: "subcategorias_incidencias",
              label: "Subcategorías",
              type: "option",
              order: 2,
            },
            {
              key: "lista_de_incidentes",
              label: "Lista de Incidentes",
              type: "option",
              order: 3,
            },
          ],
        },
        {
          id: "fallas",
          key: "fallas",
          label: "Fallas",
          order: 1,
          column: 2,
          items: [
            {
              key: "nueva_falla",
              label: "+ Nueva Falla",
              type: "link",
              href: "/incidencias?tab=falla&action=nueva_falla",
              order: 1,
            },
            {
              key: "fallas_abiertas",
              label: "Abiertas",
              type: "link",
              href: "/incidencias?tab=falla&status=abierto",
              order: 2,
            },
            {
              key: "fallas_cerradas",
              label: "Cerradas",
              type: "link",
              href: "/incidencias?tab=falla&status=resuelto",
              order: 3,
            },
            {
              key: "fallas_todas",
              label: "Todos",
              type: "link",
              href: "/incidencias?tab=falla",
              order: 4,
            },
          ],
        },
        {
          id: "configuracion-fallas",
          key: "configuracion_fallas",
          label: "Configuración",
          order: 2,
          column: 2,
          items: [
            {
              key: "conceptos_fallas",
              label: "Conceptos",
              type: "option",
              order: 1,
            },
            {
              key: "subconceptos_fallas",
              label: "Subconceptos",
              type: "option",
              order: 2,
            },
            {
              key: "lista_de_fallas",
              label: "Lista de Fallas",
              type: "option",
              order: 3,
            },
          ],
        },
        {
          id: "rondines",
          key: "rondines",
          label: "Rondines",
          order: 1,
          column: 3,
          items: [
            {
              key: "programar-rondin",
              label: "+ Programar Rondín",
              type: "link",
              href: "/rondines?tab=rondines&action=programar_rondin",
              order: 1,
            },
            {
              key: "rondines_programados",
              label: "Programados",
              type: "link",
              href: "/rondines?tab=rondines",
              order: 2,
            },
            {
              key: "rondines_matriz",
              label: "Matriz",
              type: "link",
              href: "/rondines?tab=matriz",
              order: 3,
            },
            {
              key: "rondines_calendario",
              label: "Calendario",
              type: "link",
              href: "/rondines?tab=calendario",
              order: 4,
            },
            {
              key: "rondines_incidencias",
              label: "Incidencias",
              type: "link",
              href: "/rondines?tab=incidencias",
              order: 5,
            },
            {
              key: "rondines_fotos",
              label: "Fotos",
              type: "link",
              href: "/rondines?tab=fotos",
              order: 6,
            },
            {
              key: "rondines_comentarios",
              label: "Comentarios",
              type: "link",
              href: "/rondines?tab=comentarios",
              order: 7,
            },
          ],
        },
        {
          id: "configuracion-rondines",
          key: "configuracion_rondines",
          label: "Configuración",
          order: 2,
          column: 3,
          items: [
            {
              key: "configuracion_rondines",
              label: "Configuración de rondines",
              type: "option",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      id: "activos",
      key: "activos",
      label: "Activos",
      icon: "alert",
      order: 5,
      columns: 3,
      sections: [
        {
          id: "paqueteria",
          key: "paqueteria",
          label: "Paquetería",
          order: 1,
          column: 1,
          items: [
            {
              key: "nuevo_paquete",
              label: "+ Nuevo Paquete",
              type: "link",
              href: "/articulos?action=nuevo_paquete",
              order: 1,
            },
            {
              key: "paquetes_pendientes",
              label: "Pendientes",
              type: "link",
              href: "/articulos?tab=paquetes&status=pendientes",
              order: 2,
            },
            {
              key: "paquetes_entregados",
              label: "Entregados",
              type: "link",
              href: "/articulos?tab=paquetes&status=entregados",
              order: 3,
            },
            {
              key: "paquetes_todos",
              label: "Todos",
              type: "link",
              href: "/articulos?tab=paquetes",
              order: 4,
            },
          ],
        },
        {
          id: "paqueteria-configuracion",
          key: "paqueteria_configuracion",
          label: "Configuración",
          order: 2,
          column: 1,
          items: [
            {
              key: "proveedores",
              label: "Proveedores",
              type: "option",
              order: 1,
            },
          ],
        },
        {
          id: "articulos-perdidos",
          key: "articulos_perdidos",
          label: "Artículos Perdidos",
          order: 1,
          column: 2,
          items: [
            {
              key: "nuevo_articulo_perdido",
              label: "+ Nuevo Artículo",
              type: "link",
              href: "/articulos?action=nuevo_articulo_perdido",
              order: 1,
            },
            {
              key: "articulos_perdidos_pendientes",
              label: "Pendientes",
              type: "link",
              href: "/articulos?tab=articulos_perdidos&status=pendientes",
              order: 2,
            },
            {
              key: "articulos_perdidos_entregados",
              label: "Entregados",
              type: "link",
              href: "/articulos?tab=articulos_perdidos&status=entregados",
              order: 3,
            },
            {
              key: "articulos_perdidos_todos",
              label: "Todos",
              type: "link",
              href: "/articulos?tab=articulos_perdidos",
              order: 4,
            },
          ],
        },
        {
          id: "articulos-perdidos-configuracion",
          key: "articulos_perdidos_configuracion",
          label: "Configuración",
          order: 2,
          column: 2,
          items: [
            {
              key: "categorias_articulos_perdidos",
              label: "Categorías",
              type: "option",
              order: 1,
            },
            {
              key: "lista_de_objetos",
              label: "Lista de Objetos",
              type: "option",
              order: 2,
            },
          ],
        },
        {
          id: "articulos-concesionados",
          key: "articulos_concesionados",
          label: "Artículos Concesionados",
          order: 1,
          column: 3,
          items: [
            {
              key: "nuevo_articulo_concesionado",
              label: "+ Nuevo Concesión",
              type: "link",
              href: "/articulos?action=nuevo_articulo_concesionado",
              order: 1,
            },
            {
              key: "articulos_concesionados_pendientes",
              label: "Pendientes",
              type: "link",
              href: "/articulos?tab=articulos_concesionados&status=pendientes",
              order: 2,
            },
            {
              key: "articulos_concesionados_parciales",
              label: "Parciales",
              type: "link",
              href: "/articulos?tab=articulos_concesionados&status=parciales",
              order: 3,
            },
            {
              key: "articulos_concesionados_devueltos",
              label: "Devueltos",
              type: "link",
              href: "/articulos?tab=articulos_concesionados&status=devueltos",
              order: 4,
            },
            {
              key: "articulos_concesionados_todos",
              label: "Todos",
              type: "link",
              href: "/articulos?tab=articulos_concesionados",
              order: 5,
            },
          ],
        },
        {
          id: "articulos-concesionados-configuracion",
          key: "articulos_concesionados_configuracion",
          label: "Configuración",
          order: 2,
          column: 3,
          items: [
            {
              key: "activos_fijos",
              label: "Activos Fijos",
              type: "option",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      id: "empleados",
      key: "empleados",
      label: "Empleados",
      icon: "alert",
      order: 6,
      columns: 2,
      sections: [
        {
          id: "usuarios",
          key: "usuarios",
          label: "Usuarios",
          order: 1,
          column: 1,
          items: [
            {
              key: "nuevo_empleado",
              label: "+ Nuevo Empleado",
              type: "option",
              order: 1,
            },
            {
              key: "empleados_activos",
              label: "Activos",
              type: "option",
              order: 2,
            },
            {
              key: "empleados_inactivos",
              label: "Inactivos",
              type: "option",
              order: 3,
            },
            {
              key: "empleados_todos",
              label: "Todos",
              type: "option",
              order: 4,
            },
          ],
        },
        {
          id: "departamentos-y-puestos",
          key: "departamentos_y_puestos",
          label: "Departamentos & Puestos",
          order: 1,
          column: 2,
          items: [
            {
              key: "nuevo_departamento",
              label: "+ Nuevo Departamento",
              type: "option",
              order: 1,
            },
            {
              key: "nuevo_puesto",
              label: "+ Nuevo Puesto",
              type: "option",
              order: 2,
            },
            {
              key: "todos_departamentos_y_puestos",
              label: "Todos",
              type: "option",
              order: 3,
            },
          ],
        },
        {
          id: "configuracion-departamentos-y-puestos",
          key: "configuracion_departamentos_y_puestos",
          label: "Configuración",
          order: 2,
          column: 2,
          items: [
            {
              key: "departamentos_y_puestos",
              label: "Departamentos y puestos",
              type: "option",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      id: "ubicaciones",
      key: "ubicaciones",
      label: "Ubicaciones",
      icon: "alert",
      order: 7,
      columns: 2,
      sections: [
        {
          id: "ubicaciones",
          key: "ubicaciones",
          label: "Ubicaciones",
          order: 1,
          column: 1,
          items: [
            {
              key: "nueva_ubicacion",
              label: "+ Nueva Ubicación",
              type: "option",
              order: 1,
            },
            {
              key: "ubicaciones_todas",
              label: "Todas",
              type: "option",
              order: 2,
            },
          ],
        },
        {
          id: "configuracion-ubicaciones",
          key: "configuracion_ubicaciones",
          label: "Configuración",
          order: 2,
          column: 1,
          items: [
            {
              key: "configuracion_de_seguridad",
              label: "Configuración de seguridad",
              type: "option",
              order: 1,
            },
          ],
        },
        {
          id: "areas",
          key: "areas",
          label: "Áreas",
          order: 1,
          column: 2,
          items: [
            {
              key: "nueva_area",
              label: "+ Nueva Área",
              type: "option",
              order: 1,
            },
            {
              key: "areas_disponibles",
              label: "Disponibles",
              type: "option",
              order: 2,
            },
            {
              key: "areas_todas",
              label: "Todas",
              type: "option",
              order: 3,
            },
          ],
        },
        {
          id: "configuracion-de-areas",
          key: "configuracion_areas",
          label: "Configuración",
          order: 2,
          column: 2,
          items: [
            {
              key: "tipos_de_areas",
              label: "Tipos de áreas",
              type: "option",
              order: 1,
            },
          ],
        },
      ],
    },
  ],
};
